<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <div class="col-md-12">
        <h1>Categorias <small>atualizar uma categoria</small></h1>
        <hr>
    </div>

    <div class="col-md-12">
        <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
    </div>
    
    <div class="col-md-12">
        <form method="post" action="<?= HOME ?>/categories/edit/<?= $this->category['id']; ?>">
            <div class="form-group">
                <label for="name">Nome</label>
                <input type="text" class="form-control" id="name" name="name" value="<?= $this->category['name']; ?>">
            </div>

            <div class="form-group">
                <label for="description">Descrição</label>
                <input type="text" class="form-control" id="description" name="description" value="<?= $this->category['description']; ?>">
            </div>

            <button type="submit" class="btn btn-success btn-lg pull-right">Atualizar Categoria</button>
        </form>
    </div>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
