<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <div class="col-md-12">
        <h1>Post <small>cadastrar novo</small></h1>
        <hr>
    </div>

    <div class="col-md-12">
        <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
    </div>
    
    <div class="col-md-12">
        <form method="post" action="<?= HOME ?>/posts/new">
            <div class="form-group">
                <label for="title">Título</label>
                <input type="text" class="form-control" id="title" name="title">
            </div>

            <div class="form-group">
                <label for="description">Descrição</label>
                <input type="text" class="form-control" id="description" name="description">
            </div>

            <div class="form-group">
                <label for="content">Conteúdo</label>
                <textarea name="content" id="content" cols="30" rows="10" class="form-control"></textarea>
            </div>

            <div class="form-group">
                <label for="type">Tipo</label>
                <select name="type" id="type" class="form-control">
                    <option value="">Selecione o tipo do conteúdo...</option>
                    <option value="post">Post</option>
                    <option value="page">Página</option>
                </select>
            </div>

            <div class="form-group">
                <label for="category_id">Categoria</label>
                <select name="category_id" id="category_id" class="form-control">
                    <option value="">Selecione uma categoria...</option>
                    <?php foreach($this->categories as $c) : ?>
                        <option value="<?= $c['id'] ?>"><?= $c['name'] ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="form-group">
                <label for="user_id">Autor</label>
                <select name="user_id" id="user_id" class="form-control">
                    <option value="">Selecione um autor...</option>
                    <?php foreach($this->users as $u) : ?>
                        <option value="<?= $u['id'] ?>"><?= $u['first_name'] . ' ' . $u['last_name'] ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <button type="submit" class="btn btn-success btn-lg pull-right">Salvar Post</button>
        </form>
    </div>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
