<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <div class="col-md-12">
        <h1>Usuários <small>cadastrar novo</small></h1>
        <hr>
    </div>

    <div class="col-md-12">
        <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
    </div>
    
    <div class="col-md-12">
        <form method="post" action="<?= HOME ?>/users/new">
            <div class="form-group">
                <label for="first_name">Nome</label>
                <input type="text" class="form-control" id="first_name" name="first_name">
            </div>

            <div class="form-group">
                <label for="last_name">Sobrenome</label>
                <input type="text" class="form-control" id="last_name" name="last_name">
            </div>

            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username">
            </div>

            <div class="form-group">
                <label for="password">Senha</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>

            <div class="form-group">
                <label for="password_confirm">Confirmar Senha</label>
                <input type="password" class="form-control" id="password_confirm" name="password_confirm">
            </div>

            <button type="submit" class="btn btn-success btn-lg pull-right">Salvar Usuário</button>
        </form>
    </div>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
