<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <div class="col-cd-12">
        <div class="col-md-8 pull-left">
            <div class="row">
                <h2><?= $this->post['title']; ?></h2>
                <small>Criado em <?= date('d/M/Y H:i:s', strtotime($this->post['created_at'])) ?></small>
                <hr>
            </div>
            <p><?= $this->post['description']; ?></p>
        </div>
        <div class="col-md-4 pull-right">
            <div class="row">
                <h3>Sidebar</h3>
                <hr>
            </div>

            <div class="row content">
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nulla expedita eligendi placeat vel quos sit esse pariatur laudantium, beatae cupiditate, explicabo numquam eveniet maxime. Repudiandae, voluptatum. Rerum molestiae dolore nulla!</p>
            </div>
        </div>
    </div>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
