<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <div class="jumbotron">
        <h1>Sobre</h1>
    </div>
    <div class="col-md-12">
        <h2>A Instituição</h2>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta, voluptatem at. Veniam, dolorem? Iure neque eius ab, veniam necessitatibus doloribus impedit harum corporis enim, cupiditate dolor animi? Distinctio, officia asperiores.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas tempore incidunt natus deleniti expedita? Harum explicabo in nam maxime alias soluta autem quae incidunt quia, ratione, nemo adipisci eaque magnam.</p>
        <h2>Nossas metas</h2>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iste optio esse dolore autem incidunt beatae ab perferendis molestias adipisci pariatur dicta sint veniam ex, sed aliquid doloribus. Ex, sit expedita.</p>
        <h2>Valore</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id accusamus assumenda fuga accusantium ipsam laudantium dolore similique doloribus enim nemo. Maiores culpa labore sed quaerat assumenda debitis minima praesentium iusto?</p>
    </div>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>
